FROM nexusprod.corp.intranet:4567/ubuntu:bionic
LABEL Description="This is a base image, which provides one ANT environment"

ARG user=jenkins
ARG group=jenkins
ARG uid=1341
ARG gid=1341
RUN getent group ${gid} || groupadd -g ${gid} ${group}
RUN useradd -c "Jenkins user" -d /home/${user} -u ${uid} -g ${gid} -m ${user}

VOLUME /mvn

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev && \
    apt-get install -y curl net-tools build-essential software-properties-common bzip2 libbz2-dev git wget unzip vim openjdk-8-jdk && \
    apt-get install -y git xz-utils xvfb libxi6 libgconf-2-4 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV INSTALL_DIR=${INSTALL_DIR:-/usr}

RUN apt-get update && \
    apt-get install -y ant && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN usermod -a -G root ${user}

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV ANT_HOME=/usr/share/ant

ENV PATH=${PATH}:${JAVA_HOME}/bin:${ANT_HOME}/bin:/usr/bin
RUN java -version
RUN ant -version